openapi: 3.0.0
info:
  title: Cachie API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /search:
    post:
      summary: Add a search query to Cachie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                search_query:
                  type: string
      responses:
        '200':
          description: OK
  /analyse:
    get:
      summary: Analyse search queries in Cachie
      parameters:
        - in: query
          name: analysis_token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
